version: '3'

services:
  db:
    build:
      context: ./kakeibo-db
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
      LC_ALL: ja_JP.UTF-8
    ports:
        - ${DB_PORT}:3306
    volumes:
        - db-store:/var/lib/mysql

  node:
    build: 
      context: ./kakeibo-node
      dockerfile: Dockerfile
    volumes:
      - ./kakeibo-node:/usr/src/app
    ports:
      - '49160:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npx nodemon
    depends_on:
      - db

  react:
    build: 
      context: ./kakeibo-react
      dockerfile: Dockerfile
    volumes:
      - ./kakeibo-react:/usr/src/app
    ports:
      - '49170:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - node

volumes:
  db-store:
