version: '3'

services:
  db:
    image: mysql:8.0.32
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - db-store:/var/lib/mysql
    - ./kakeibo-db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./kakeibo-db/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  node:
    build: 
      context: ./kakeibo-node
      dockerfile: Dockerfile
    volumes:
      - ./kakeibo-node:/usr/src/app
      - node-modules_backend:/usr/src/app/node_modules
    ports:
      - '49160:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npx nodemon
    depends_on:
      db:
        condition: service_healthy

  react:
    build: 
      context: ./kakeibo-react
      dockerfile: Dockerfile
    volumes:
      - ./kakeibo-react:/usr/src/app
      - node-modules_frontend:/usr/src/app/node_modules
    ports:
      - '49170:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - node

volumes:
  db-store:
  node-modules_backend:
  node-modules_frontend:
